# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import optimization_pb2 as optimization__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in optimization_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OptimizationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AllocateResources = channel.unary_unary(
                '/optimization.OptimizationService/AllocateResources',
                request_serializer=optimization__pb2.AllocationRequest.SerializeToString,
                response_deserializer=optimization__pb2.AllocationResponse.FromString,
                _registered_method=True)
        self.DualOptimization = channel.unary_unary(
                '/optimization.OptimizationService/DualOptimization',
                request_serializer=optimization__pb2.DualOptimizationRequest.SerializeToString,
                response_deserializer=optimization__pb2.DualOptimizationResponse.FromString,
                _registered_method=True)
        self.PredictQoS = channel.unary_unary(
                '/optimization.OptimizationService/PredictQoS',
                request_serializer=optimization__pb2.QoSPredictionRequest.SerializeToString,
                response_deserializer=optimization__pb2.QoSPredictionResponse.FromString,
                _registered_method=True)


class OptimizationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AllocateResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DualOptimization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictQoS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptimizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AllocateResources': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateResources,
                    request_deserializer=optimization__pb2.AllocationRequest.FromString,
                    response_serializer=optimization__pb2.AllocationResponse.SerializeToString,
            ),
            'DualOptimization': grpc.unary_unary_rpc_method_handler(
                    servicer.DualOptimization,
                    request_deserializer=optimization__pb2.DualOptimizationRequest.FromString,
                    response_serializer=optimization__pb2.DualOptimizationResponse.SerializeToString,
            ),
            'PredictQoS': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictQoS,
                    request_deserializer=optimization__pb2.QoSPredictionRequest.FromString,
                    response_serializer=optimization__pb2.QoSPredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'optimization.OptimizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('optimization.OptimizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OptimizationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AllocateResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/optimization.OptimizationService/AllocateResources',
            optimization__pb2.AllocationRequest.SerializeToString,
            optimization__pb2.AllocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DualOptimization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/optimization.OptimizationService/DualOptimization',
            optimization__pb2.DualOptimizationRequest.SerializeToString,
            optimization__pb2.DualOptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictQoS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/optimization.OptimizationService/PredictQoS',
            optimization__pb2.QoSPredictionRequest.SerializeToString,
            optimization__pb2.QoSPredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
